apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: workload-app
    app.kubernetes.io/instance: workload-app
    app.kubernetes.io/name: workload-app
  name: workload-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workload-app
      app.kubernetes.io/instance: workload-app
      app.kubernetes.io/name: workload-app
  template:
    metadata:
      labels:
        app: workload-app
        app.kubernetes.io/instance: workload-app
        app.kubernetes.io/name: workload-app
    spec:
      containers:
      - image: ghcr.io/j-kokoszka/workload-app:latest
        imagePullPolicy: Always
        name: workload-app
        resources:
          limits:
            cpu: 500m
            memory: 500M
