apiVersion: v1
kind: Service
metadata:
  labels:
    app: workload-app
    app.kubernetes.io/instance: workload-app
    app.kubernetes.io/name: workload-app
    release: kube-prometheus-stack
  name: workload-app-service
  namespace: default
spec:
  ports:
  - port: 8080
    name: http-metrics
    protocol: TCP
    targetPort: 8080
  selector:
    app: workload-app
    app.kubernetes.io/instance: workload-app
    app.kubernetes.io/name: workload-app
    release: kube-prometheus-stack
  type: ClusterIP
