apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: workload-app-vpa
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: workload-app
  updatePolicy:
    updateMode: "Recreate"   # Allowed: Off | Initial | Recreate | Auto
  resourcePolicy:
    containerPolicies:
    - containerName: "*"
      minAllowed:
        cpu: 100m
      maxAllowed:
        cpu: 2
      controlledResources:
        - cpu
        - memory

