apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shell-operator
  namespace: default
  labels:
    app: shell-operator
    release: kube-prometheus-stack
spec:
  endpoints:
  - interval: 1s
    path: /metrics
    port: http-metrics
  jobLabel: shell-operator
  selector:
    matchLabels:
      app: shell-operator
      release: kube-prometheus-stack
