apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: autoscalerpolicies.example.com
spec:
  group: example.com
  names:
    plural: autoscalerpolicies
    singular: autoscalerpolicy
    kind: AutoScalerPolicy
    shortNames:
      - asp
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                targetDeployment:
                  type: string
                mode:
                  type: string
                  enum: ["horizontal", "vertical"]
                minReplicas:
                  type: integer
                maxReplicas:
                  type: integer

