{
 "title": "Workload app overview",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pod", "label": "pod", "query": { "query": "label_values(pod)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU usage of pods",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{container=\"workload-app\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ilość żądań na sekundę, HTTP 200 [req/s]",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(istio_requests_total{service=\"workload-app-service\",response_code=\"200\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "type": "barchart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (response_code) (\n  rate(istio_requests_total{service=\"workload-app-service\"}[5s])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ilość replik aplikacji workload-app",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_spec_replicas{deployment=\"workload-app\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ilość  żądań http na sekundę [req/s]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (handler) (rate(http_requests_total{service=\"workload-app-service\"}[5s]))",
     "legendFormat": "{{handler}}"
    }
   ]
  }
 ]
}