name: Python FastAPI CI

on:
  push:
    branches: [ main ]
    paths:
      - 'experiments/workload-app/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'experiments/workload-app/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3. Install Poetry
      - name: Install Poetry
        run: pip install poetry

      # 4. Install dependencies for workload-app
      - name: Install dependencies
        working-directory: experiments/workload-app
        run: poetry install --no-root

      # 5. Run tests
      - name: Run tests
        working-directory: experiments/workload-app
        run: poetry run pytest tests

